apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: to-do-postgres-pv-claim
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi